memory_limit = 256M
upload_max_filesize = 25M
post_max_size = 25M
max_execution_time = 60
max_input_vars = 5000
date.timezone = Africa/Abidjan
expose_php = Off

display_errors = Off
log_errors = On
error_log = /dev/stderr

session.cookie_secure = 1
session.cookie_httponly = 1
session.cookie_samesite = "Lax"
